baseURL: "https://eiken59.github.io/"
title: Yung-Hsuan's Website
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Posts
          url: posts/
          weight: 1

params:
    description: "This website hosts CHANG Yung-Hsuan's curriculum vitae, contact information, and academic backgrounds."
    author: CHANG Yung-Hsuan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January, 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    mainSections: ["page"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: false
    ShowWordCount: false
    UseHugoToc: false
    comments: false
    math: true
    footer:
        text: "<em>On dirige ce qu'on affronte. C'est là qu'on trouve la magie.</em>"
        hideCopyright: true
    profileMode:
          enabled: true
          title: CHANG Yung-Hsuan (張永璿)
          subtitle: |
            &nbsp;

            I'm Yung-Hsuan Chang, also known as Eiken. I am completing my B.S. in Applied Mathematics at National Yang Ming Chiao Tung University, complemented by an exchange year at École polytechnique in France. My academic background spans research in probability (random walks), statistics, machine learning, and mathematical communication.

            &nbsp;

            Actively preparing for graduate studies and a career in actuarial science, I have passed SOA Exams P and FM. I am looking forward to actuarial and data-driven roles where I can leverage my quantitative training, programming proficiency, and multilingual communication skills.

            &nbsp;
          imageUrl: "pp.png"
          imageWidth: 180
          imageHeight: auto

    socialIcons:
        - name: CV
          url: eiken59_CV.pdf
        - name: Email
          url: mailto:eiken59@icloud.com
        - name: GitHub
          url: https://github.com/eiken59/
        - name: LinkedIn
          url: https://www.linkedin.com/in/eiken59/
        # - name: Google Sites
        #   url: https://sites.google.com/view/eiken59/
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat

    assets:
        disableScrollBarStyle: true
        favicon: fairy_icon_transparent.png
        favicon16x16: fairy_icon_transparent.png
        favicon32x32: fairy_icon_transparent.png
        apple_touch_icon: fairy_icon_transparent.png
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "CHANG Yung-Hsuan"
      icon: fairy_icon_transparent.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: true
        startLevel: 2