baseURL: "https://eiken59.github.io/"
title: Yung-Hsuan's Website
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Posts
          url: posts/
          weight: 1

params:
    description: "This website hosts CHANG Yung-Hsuan's curriculum vitae, contact information, and academic backgrounds."
    author: CHANG Yung-Hsuan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    mainSections: ["page"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: false
    ShowWordCount: false
    UseHugoToc: false
    comments: false
    math: true
    footer:
        text: "<em>On dirige ce qu'on affronte. C'est là qu'on trouve la magie.</em>"
        hideCopyright: true
    profileMode:
          enabled: true
          title: CHANG Yung-Hsuan (張永璿)
          subtitle: |
            &nbsp;

            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I'm Yung-Hsuan Chang, also known as Eiken. I am finishing my undergraduate study at National Yang Ming Chiao Tung University with research experience in random walks, as well as experience in tutoring, curriculum design, and mathematical communication.

            &nbsp;

            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;I am preparing for graduate study in actuarial science in the United States and am interested in actuarial, analytical, and other knowledge-intensive roles where I can contribute quantitative training, clear writing, and multilingual communication skills.

            &nbsp;
          imageUrl: "pp.png"
          imageWidth: 200
          imageHeight: auto

    socialIcons:
        - name: CV
          url: eiken59_CV.pdf
        - name: Email
          url: mailto:eiken59@icloud.com
        - name: GitHub
          url: https://github.com/eiken59/
        - name: LinkedIn
          url: https://www.linkedin.com/in/eiken59/
        # - name: Google Sites
        #   url: https://sites.google.com/view/eiken59/
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat

    assets:
        disableScrollBarStyle: true
        favicon: fairy_noBG.ico
        favicon16x16: fairy-16x16.png
        favicon32x32: fairy-32x32.png
        apple_touch_icon: fairy_noBG.png
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "CHANG Yung-Hsuan"
      icon: fairy_noBG.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: true
        startLevel: 2